-- KerfSuite Database Schema

-- 1. Create the Workspaces table
CREATE TABLE IF NOT EXISTS public.workspaces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Create the Users extension table (links auth.users to workspaces)
-- Supabase handles auth.users, so we just map their ID here
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    workspace_id UUID REFERENCES public.workspaces(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member', -- 'admin', 'member'
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. Create the License Slots table (The core CDKey tracker)
CREATE TABLE IF NOT EXISTS public.license_slots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    app TEXT NOT NULL DEFAULT 'kerfcut', -- 'kerfcut', 'kerfstock'
    cdkey TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL DEFAULT 'waiting', -- 'waiting', 'active', 'revoked'
    bound_machine_id TEXT, -- Populated when a machine redeems the key
    redeemed_at TIMESTAMPTZ,
    created_by UUID REFERENCES public.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==========================================
-- KERFSTOCK INVENTORY TABLES
-- ==========================================

-- 4. Locations (Hierarchical storage)
CREATE TABLE IF NOT EXISTS public.locations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    parent_id UUID REFERENCES public.locations(id) ON DELETE CASCADE,  -- NULL = top-level site
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Materials (Definitions, not physical objects)
CREATE TABLE IF NOT EXISTS public.materials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    thickness NUMERIC,
    unit TEXT NOT NULL DEFAULT 'mm',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.users(id)
);

-- 6. Assets (Individual physical objects)
CREATE TABLE IF NOT EXISTS public.assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    material_id UUID NOT NULL REFERENCES public.materials(id) ON DELETE RESTRICT,
    system_name TEXT NOT NULL UNIQUE,       -- e.g. OFFCUT-0142
    display_name TEXT,                        -- optional user-defined name
    width NUMERIC NOT NULL,
    height NUMERIC NOT NULL,
    asset_type TEXT NOT NULL,               -- 'full_sheet', 'remnant', 'offcut', 'custom'
    status TEXT NOT NULL DEFAULT 'available', -- 'available', 'reserved', 'consumed', 'disposed', 'damaged'
    location_id UUID REFERENCES public.locations(id) ON DELETE SET NULL,
    source_asset_id UUID REFERENCES public.assets(id),  -- parent asset if generated by cut
    job_reference TEXT,                        -- KerfCut job ID if applicable
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.users(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID REFERENCES public.users(id)
);

-- 7. Asset Events (Immutable audit log)
CREATE TABLE IF NOT EXISTS public.asset_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL REFERENCES public.assets(id) ON DELETE CASCADE,
    workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    performed_by UUID REFERENCES public.users(id),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes TEXT,
    metadata JSONB           -- flexible payload per event type
);

-- 8. Tags & Asset Tags
CREATE TABLE IF NOT EXISTS public.tags (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    UNIQUE (workspace_id, name)
);

CREATE TABLE IF NOT EXISTS public.asset_tags (
    asset_id UUID NOT NULL REFERENCES public.assets(id) ON DELETE CASCADE,
    tag_id UUID NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (asset_id, tag_id)
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.license_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_tags ENABLE ROW LEVEL SECURITY;

-- 9. Policies

-- Workspace Isolation Policies
DROP POLICY IF EXISTS "Users view own workspace" ON public.workspaces;
CREATE POLICY "Users view own workspace" ON public.workspaces FOR SELECT USING (id IN (SELECT workspace_id FROM public.users WHERE users.id = auth.uid()));

DROP POLICY IF EXISTS "Users view workspace peers" ON public.users;
CREATE POLICY "Users view workspace peers" ON public.users FOR SELECT USING (workspace_id IN (SELECT workspace_id FROM public.users WHERE users.id = auth.uid()));

DROP POLICY IF EXISTS "Users manage workspace licenses" ON public.license_slots;
CREATE POLICY "Users manage workspace licenses" ON public.license_slots FOR ALL USING (workspace_id IN (SELECT workspace_id FROM public.users WHERE users.id = auth.uid()));

-- KerfStock RLS Policies
DROP POLICY IF EXISTS "Workspace isolation for locations" ON public.locations;
CREATE POLICY "Workspace isolation for locations" ON public.locations FOR ALL USING (workspace_id IN (SELECT workspace_id FROM public.users WHERE users.id = auth.uid()));

DROP POLICY IF EXISTS "Workspace isolation for materials" ON public.materials;
CREATE POLICY "Workspace isolation for materials" ON public.materials FOR ALL USING (workspace_id IN (SELECT workspace_id FROM public.users WHERE users.id = auth.uid()));

DROP POLICY IF EXISTS "Workspace isolation for assets" ON public.assets;
CREATE POLICY "Workspace isolation for assets" ON public.assets FOR ALL USING (workspace_id IN (SELECT workspace_id FROM public.users WHERE users.id = auth.uid()));

DROP POLICY IF EXISTS "Workspace isolation for asset events" ON public.asset_events;
CREATE POLICY "Workspace isolation for asset events" ON public.asset_events FOR ALL USING (workspace_id IN (SELECT workspace_id FROM public.users WHERE users.id = auth.uid()));

DROP POLICY IF EXISTS "Workspace isolation for tags" ON public.tags;
CREATE POLICY "Workspace isolation for tags" ON public.tags FOR ALL USING (workspace_id IN (SELECT workspace_id FROM public.users WHERE users.id = auth.uid()));

DROP POLICY IF EXISTS "Workspace isolation for asset tags" ON public.asset_tags;
CREATE POLICY "Workspace isolation for asset tags" ON public.asset_tags FOR ALL USING (
    asset_id IN (
        SELECT id FROM public.assets WHERE workspace_id IN (SELECT workspace_id FROM public.users WHERE users.id = auth.uid())
    )
);

-- ==========================================
-- TRIGGERS
-- ==========================================

-- 10. Helper Trigger: Auto-create User Profile on Auth Signup
-- This trigger automatically creates a row in public.users when you sign up in Supabase
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
DECLARE
    default_workspace_id UUID;
BEGIN
    -- For V1, we just create a default workspace for the new admin if none exists
    -- In a real SaaS, this would be handled by a proper onboarding flow
    INSERT INTO public.workspaces (name) VALUES ('My Workshop') RETURNING id INTO default_workspace_id;
    
    INSERT INTO public.users (id, workspace_id, email, role)
    VALUES (new.id, default_workspace_id, new.email, 'admin');
    
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if exists to prevent duplicates on re-run
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
